Make GPU offload library linking behaviour configurable
ecmwf-ifs/field_api pull request #54
Opened 2024-06-19 04:06 UTC by awnawab

When linking a single FIELD_API build to multiple libraries, we may want to only selectively enable GPU offload in the downstream target libraries.

This PR enables optional private linking of OpenACC and cuda to libfield_api_dp/sp to prevent FIELD_API from always exporting GPU offload libraries to downstream targets.

(I am on leave so will probably be slow to respond to requested changes, apologies in advance!)

2024-06-19 09:56 UTC, mlange05 requested changes
Overall, I agree we need to ensure that the compiler flags are not propagated through "PUBLIC" linking of OpenACC / CUDA et al. However, I think we might be able to just switch this to INTERFACE_LIBS to avoid compiler flags seeping upstream, while ensuring that linker flags are propagated correctly. Would you mind verifying this when you're back, @awnawab ?

2024-06-19 09:56 UTC, mlange05 commented on CMakeLists.txt
> -      PUBLIC_LIBS
As discussed offline, I think the fundamental problem is that we want to propagate link flags, but not compiler flags. I tried a suggestion by @reuterbal to switch this to
```
INTERFACE_LIBS
    $<${HAVE_ACC}:OpenACC::OpenACC_Fortran>
```
I think this works for our use case, so potentially the additional configuration option is not needed after all?

2024-07-22 14:08 UTC, awnawab commented
Closing this as it was superseded by #56.

2024-07-22 14:09 UTC, awnawab commented
Closing this as it was superseded by #56.

2024-07-22 14:09 UTC, closed without merging