Add CPU only support for CCE17
ecmwf-ifs/field_api pull request #67
Opened 2024-11-29 17:47 UTC by awnawab

This PR provides several fixes needed to build and use FIELD_API using the Cray Fortran. Note that GPU offload is still only supported for NVHPC; Cray OpenACC support will be added at a later date.

It is a little surprising how many problems Cray Fortran had with FIELD_API given that it works with gnu, intel (old and llvm) and nvhpc. Nevertheless, the fixes are reasonably clean. The one exception is the FieldGang, for which the cray compiler cannot resolve the polymorphism, and I simply disable it. Interestingly, cce15 can but not newer compilers. cce15 was beset with many other problems though, so there is no benefit in enabling the FieldGang for cce15 and older.

2024-11-29 17:47 UTC, FussyDuck commented
[![CLA assistant check](https://bol-claassistant.ecmwf.int:443/pull/badge/not_signed)](https://bol-claassistant.ecmwf.int:443/ecmwf-ifs/field_api?pullRequest=67) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://bol-claassistant.ecmwf.int:443/ecmwf-ifs/field_api?pullRequest=67) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: awnawab<br/>:x: MichaelSt98<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bol-claassistant.ecmwf.int:443/check/ecmwf-ifs/field_api?pullRequest=67) it.</sub>

2024-11-29 17:49 UTC, awnawab commented
FYI @ioanhadade

2024-11-30 07:14 UTC, pmarguinaud commented on field_RANKSUFF_gather_module.fypp
What is the problem with generic INTERFACE here ? Why did you have to move their definition in other files ?

2024-11-30 17:36 UTC, awnawab commented on field_RANKSUFF_gather_module.fypp
We were previously defining a generic interface in each field_RANKSUFF_gather_module, and then importing these interfaces in field_gathscat_module. When building field_gathscat_module, the cray compiler complained that the same symbol (the generic interfaces all had the same name of course) is defined in multiple modules. The cleanest fix I could think was to simply move the definition of the interface into field_gathscat_module.

2024-12-01 22:16 UTC, ioanhadade commented
> FYI @ioanhadade

Thanks, can confirm this builds with cce 16.0.1 and 17.0.1

2024-12-02 12:12 UTC, mlange05 requested changes
Looks good to me (untested though). Only comment I have is that we should probably update the README to reflect the changes in outward-facing CMake options.

2024-12-02 12:12 UTC, mlange05 commented on CMakeLists.txt
> +                    CONDITION CMAKE_Fortran_COMPILER_ID MATCHES "PGI|NVHPC")
I think we want to make this explicit in the README under supported features.

2024-12-02 12:12 UTC, mlange05 commented on CMakeLists.txt
> +    CONDITION (NOT CMAKE_Fortran_COMPILER_ID MATCHES "Cray")
Same here, should we mention this in the "supported features" section of the README?

2024-12-02 14:58 UTC, mlange05 approved these changes
Looks great now from my side. 👍

2024-12-03 08:18 UTC, pmarguinaud approved these changes

2024-12-03 08:42 UTC, awnawab commented on field_RANKSUFF_gather_module.fypp
Yes I agree, and in fact we have the same pattern in field_factory_module which the compiler seems to accept. Good idea, I will make a reproducer and share it with HPE.

2024-12-03 11:01 UTC, dareg approved these changes
I don't have access to a cray compiler so I've just checked that it still works with our gpupack setup.

2024-12-03 12:34 UTC, awnawab commented
Thanks all for the feedback and reviews 🙏  merging now

2024-12-03 12:35 UTC, merged